### ISSUE TITLE
[bug] react-three-fiber SDK errors locally when no ad is returned

### ISSUE THREAD

**Issue by limbofeather** [zestyxyz/ads-sdk#193]
Handle what happens when the URL is empty (should default to https://zesty.xyz)

**Comment by msub2** [comment]
After resolving bundling issues with the existing R3F tests I haven't been able to reproduce this, the default banner is loading as expected when no ad is available. This is on a placeholder ad unit though, it's possible it might happen with a live ad server response, will try and verify that

**Comment by msub2** [comment]
I don't believe this is an issue anymore (I've never been able to reproduce), can reopen if we see this again.
